site_name: SDKBOX文档
pages:
- 介绍: 'index.md'
- 安装器: 'installer.md'
- 插件:
    - 'Achievements':
        - 'Cocos2d-x v3.x':
            - 'Achievements with C++': 'plugins/achievement/v3-cpp.md'
            - 'Achievements with Javascript': 'plugins/achievement/v3-js.md'
            - 'Achievements with Lua': 'plugins/achievement/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Achievements with C++': 'plugins/achievement/v2-cpp.md'
            - 'Achievements with Javascript': 'plugins/achievement/v2-js.md'
            - 'Achievements with Lua': 'plugins/achievement/v2-lua.md'
    - 'AdColony':
        - 'Cocos2d-x v3.x':
            - 'AdColony with C++': 'plugins/adcolony/v3-cpp.md'
            - 'AdColony with JS': 'plugins/adcolony/v3-js.md'
            - 'AdColony with Lua': 'plugins/adcolony/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'AdColony with C++': 'plugins/adcolony/v2-cpp.md'
            - 'AdColony with Javascript': 'plugins/adcolony/v2-js.md'
            - 'AdColony with Lua': 'plugins/adcolony/v2-lua.md'
    - 'AgeCheq':
        - 'Cocos2d-x v3.x':
            - 'AgeCheq with C++': 'plugins/agecheq/v3-cpp.md'
            - 'AgeCheq with Javascript': 'plugins/agecheq/v3-js.md'
            - 'AgeCheq with Lua': 'plugins/agecheq/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'AgeCheq with C++': 'plugins/agecheq/v2-cpp.md'
            - 'AgeCheq with Javascript': 'plugins/agecheq/v2-js.md'
            - 'AgeCheq with Lua': 'plugins/agecheq/v2-lua.md'
    - 'Appodeal':
        - 'Cocos2d-x v3.x':
            - 'Appodeal with C++': 'plugins/appodeal/v3-cpp.md'
            - 'Appodeal with Javascript': 'plugins/appodeal/v3-js.md'
            - 'Appodeal with Lua': 'plugins/appodeal/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Appodeal with C++': 'plugins/appodeal/v2-cpp.md'
            - 'Appodeal with Javascript': 'plugins/appodeal/v2-js.md'
            - 'Appodeal with Lua': 'plugins/appodeal/v2-lua.md'
    - 'Bee7':
        - 'Cocos2d-x v3.x':
            - 'Bee7 with C++': 'plugins/bee7/v3-cpp.md'
            - 'Bee7 with Javascript': 'plugins/bee7/v3-js.md'
            - 'Bee7 with Lua': 'plugins/bee7/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Bee7 with C++': 'plugins/bee7/v2-cpp.md'
            - 'Bee7 with Javascript': 'plugins/bee7/v2-js.md'
            - 'Bee7 with Lua': 'plugins/bee7/v2-lua.md'
    - 'Chartboost':
        - 'Cocos2d-x v3.x':
            - 'Chartboost with C++': 'plugins/chartboost/v3-cpp.md'
            - 'Chartboost with Javascript': 'plugins/chartboost/v3-js.md'
            - 'Chartboost with Lua': 'plugins/chartboost/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Chartboost with C++': 'plugins/chartboost/v2-cpp.md'
            - 'Chartboost with Javascript': 'plugins/chartboost/v2-js.md'
            - 'Chartboost with Lua': 'plugins/chartboost/v2-lua.md'
    - 'Facebook':
        - 'Cocos2d-x v3.x':
            - 'Facebook with C++': 'plugins/facebook/v3-cpp.md'
            - 'Facebook with Javascript': 'plugins/facebook/v3-js.md'
            - 'Facebook with Lua': 'plugins/facebook/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Facebook with C++': 'plugins/facebook/v2-cpp.md'
            - 'Facebook with Javascript': 'plugins/facebook/v2-js.md'
            - 'Facebook with Lua': 'plugins/facebook/v2-lua.md'
    - 'Flurry Analytics':
        - 'Cocos2d-x v3.x':
            - 'Flurry with C++': 'plugins/flurryanalytics/v3-cpp.md'
            - 'Flurry with Javascript': 'plugins/flurryanalytics/v3-js.md'
            - 'Flurry with Lua': 'plugins/flurryanalytics/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Flurry with C++': 'plugins/flurryanalytics/v2-cpp.md'
            - 'Flurry with Javascript': 'plugins/flurryanalytics/v2-js.md'
            - 'Flurry with Lua': 'plugins/flurryanalytics/v2-lua.md'
    - 'Fyber':
        - 'Cocos2d-x v3.x':
            - 'Fyber with C++': 'plugins/fyber/v3-cpp.md'
            - 'Fyber with Javascript': 'plugins/fyber/v3-js.md'
            - 'Fyber with Lua': 'plugins/fyber/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Fyber with C++': 'plugins/fyber/v2-cpp.md'
            - 'Fyber with Javascript': 'plugins/fyber/v2-js.md'
            - 'Fyber with Lua': 'plugins/fyber/v2-lua.md'
    - 'Google Analytics':
        - 'Cocos2d-x v3.x':
            - 'Google Analytics with C++': 'plugins/googleanalytics/v3-cpp.md'
            - 'Google Analytics with Javascript': 'plugins/googleanalytics/v3-js.md'
            - 'Google Analytics with Lua': 'plugins/googleanalytics/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Google Analytics with C++': 'plugins/googleanalytics/v2-cpp.md'
            - 'Google Analytics with Javascript': 'plugins/googleanalytics/v2-js.md'
            - 'Google Analytics with Lua': 'plugins/googleanalytics/v2-lua.md'
    - 'IAP':
        - 'Cocos2d-x v3.x':
            - 'In-App Purchases(IAP) with C++': 'plugins/iap/v3-cpp.md'
            - 'In-App Purchases(IAP) with Javascript': 'plugins/iap/v3-js.md'
            - 'In-App Purchases(IAP) with Lua': 'plugins/iap/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'In-App Purchases(IAP) with C++': 'plugins/iap/v2-cpp.md'
            - 'In-App Purchases(IAP) with Javascript': 'plugins/iap/v2-js.md'
            - 'In-App Purchases(IAP) with Lua': 'plugins/iap/v2-lua.md'
    - 'Kochava':
        - 'Cocos2d-x v3.x':
            - 'Kochava with C++': 'plugins/kochava/v3-cpp.md'
            - 'Kochava with Javascript': 'plugins/kochava/v3-js.md'
            - 'Kochava with Lua': 'plugins/kochava/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Kochava with C++': 'plugins/kochava/v2-cpp.md'
            - 'Kochava with Javascript': 'plugins/kochava/v2-js.md'
            - 'Kochava with Lua': 'plugins/kochava/v2-lua.md'
    - 'Leaderboard':
        - 'Cocos2d-x v3.x':
            - 'Leaderboard with C++': 'plugins/leaderboard/v3-cpp.md'
            - 'Leaderboard with Javascript': 'plugins/leaderboard/v3-js.md'
            - 'Leaderboard with Lua': 'plugins/leaderboard/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Leaderboard with C++': 'plugins/leaderboard/v2-cpp.md'
            - 'Leaderboard with Javascript': 'plugins/leaderboard/v2-js.md'
            - 'Leaderboard with Lua': 'plugins/leaderboard/v2-lua.md'
    - 'Playphone':
        - 'Cocos2d-x v3.x':
            - 'Playphone with C++': 'plugins/playphone/v3-cpp.md'
            - 'Playphone with Javascript': 'plugins/playphone/v3-js.md'
            - 'Playphone with Lua': 'plugins/playphone/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Playphone with C++': 'plugins/playphone/v2-cpp.md'
            - 'Playphone with Javascript': 'plugins/playphone/v2-js.md'
            - 'Playphone with Lua': 'plugins/playphone/v2-lua.md'
    - 'Ratings & Reviews':
        - 'Cocos2d-x v3.x':
            - 'App Rating & Review with C++': 'plugins/review/v3-cpp.md'
            - 'App Rating & Review with Javascript': 'plugins/review/v3-js.md'
            - 'App Rating & Review with Lua': 'plugins/review/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'App Rating & Review with C++': 'plugins/review/v2-cpp.md'
            - 'App Rating & Review with Javascript': 'plugins/review/v2-js.md'
            - 'App Rating & Review with Lua': 'plugins/review/v2-lua.md'
    - 'SOOMLA Grow':
        - 'Cocos2d-x v3.x':
            - 'SOOMLA Grow with C++': 'plugins/soomlagrow/v3-cpp.md'
            - 'SOOMLA Grow with Javascript': 'plugins/soomlagrow/v3-js.md'
            - 'SOOMLA Grow with Lua': 'plugins/soomlagrow/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'SOOMLA Grow with C++': 'plugins/soomlagrow/v2-cpp.md'
            - 'SOOMLA Grow with Javascript': 'plugins/soomlagrow/v2-js.md'
            - 'SOOMLA Grow with Lua': 'plugins/soomlagrow/v2-lua.md'
    - 'Tune':
        - 'Cocos2d-x v3.x':
            - 'Tune with C++': 'plugins/tune/v3-cpp.md'
            - 'Tune with Javascript': 'plugins/tune/v3-js.md'
            - 'Tune with Lua': 'plugins/tune/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Tune with C++': 'plugins/tune/v2-cpp.md'
            - 'Tune with Javascript': 'plugins/tune/v2-js.md'
            - 'Tune with Lua': 'plugins/tune/v2-lua.md'
    - 'Valuepotion':
        - 'Cocos2d-x v3.x':
            - 'Valuepotion with C++': 'plugins/valuepotion/v3-cpp.md'
            - 'Valuepotion with Javascript': 'plugins/valuepotion/v3-js.md'
            - 'Valuepotion with Lua': 'plugins/valuepotion/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Valuepotion with C++': 'plugins/valuepotion/v2-cpp.md'
            - 'Valuepotion with Javascript': 'plugins/valuepotion/v2-js.md'
            - 'Valuepotion with Lua': 'plugins/valuepotion/v2-lua.md'
    - 'Vungle':
        - 'Cocos2d-x v3.x':
            - 'Vungle with C++': 'plugins/vungle/v3-cpp.md'
            - 'Vungle with Javascript': 'plugins/vungle/v3-js.md'
            - 'Vungle with Lua': 'plugins/vungle/v3-lua.md'
        - 'Cocos2d-x v2.x':
            - 'Vungle with C++': 'plugins/vungle/v2-cpp.md'
            - 'Vungle with Javascript': 'plugins/vungle/v2-js.md'
            - 'Vungle with Lua': 'plugins/vungle/v2-lua.md'
- 关于: 'release-note.md'

theme: mkdocs
theme_dir: 'custom_theme'
# theme: readthedocs

google_analytics: ['UA-70044300-2', 'docs.sdkbox.com/zh']
